# Generated by Django 2.0.3 on 2018-04-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180401_0702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='watcheddomain',
            table='watched_domains',
        ),
    ]
