# Generated by Django 2.0.3 on 2018-04-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180401_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelTable(
            name='domain',
            table='domains',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
