# Generated by Django 2.0.3 on 2018-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180401_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
